#!/usr/bin/env ruby

require 'erb'
require 'ostruct'

$stdout.print ERB.new(
  File.read('templates/links.html.erb')
).result(
  OpenStruct.new(
    links: ARGF.read.scan(/^([&\w -]+)\n={16,}\n/) {|section|
      [section, ARGF.read.scan(/\*\s+(.+?)\s+<(.+?)>\s+(.+)\n/)]
    }
  ).instance_eval { binding }
)

